name: Go Lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@main
