name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main

  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main
