name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main

  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@4ebcdf92829ed99e2415853b7122f808008b23bf # main
